<a href="https://colab.research.google.com/github/Mahrokh-Eb/Machine-Learning-With-Python/blob/master/1_1_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
!python --version

Python 3.7.12


In [3]:
print(np.__version__)

1.19.5


In [4]:
#dir(np)

In [5]:
#help(np.where)

In [7]:
#np.where?

In [8]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [9]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(np.where(x>5, x, 0))

[[0 0 0]
 [0 0 6]
 [7 8 9]]


In [11]:
print(np.array([1,2,3]))

[1 2 3]


In [12]:
print(type)

<class 'type'>


In [13]:
print(type(x))

<class 'numpy.ndarray'>


In [14]:
A = np.array([[1,2,3], [4,5,6]])

In [15]:
print(A)

[[1 2 3]
 [4 5 6]]


In [16]:
print(type(A))

<class 'numpy.ndarray'>


In [17]:
print(A.shape)

(2, 3)


In [18]:
print(x.shape)

(3, 3)


In [19]:
print(x.shape[0])

3


In [20]:
 print(np.reshape(A, (3,2)))

[[1 2]
 [3 4]
 [5 6]]


## **Reshape a matrix from column to row vector**

In [21]:
print(np.reshape(A,(1, -1)))

[[1 2 3 4 5 6]]


In [22]:
print(np.reshape(A, (-1, 1)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [23]:
 print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Reshape to two-dimenssion

In [24]:
y = np.array([1,2,3])

In [25]:
print(y[ None, :])

[[1 2 3]]


In [26]:
print(y[:, None])

[[1]
 [2]
 [3]]


In [27]:
print(y[:, np.newaxis])

[[1]
 [2]
 [3]]


# Array dimenssion

In [28]:
print(x.ndim)

2


In [29]:
print(y.ndim)

1


# Data type

In [30]:
print(x.dtype)

int64


In [31]:
c= np.array([1,2,3], dtype=np.float32)

In [32]:
print(c)

[1. 2. 3.]


In [34]:
print(np.arange(1, 20, step=2))

[ 1  3  5  7  9 11 13 15 17 19]


In [36]:
#np.arange?