<a href="https://colab.research.google.com/github/Mahrokh-Eb/Machine-Learning-With-Python/blob/master/1_1_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
!python --version

Python 3.7.12


In [3]:
print(np.__version__)

1.19.5


In [4]:
#dir(np)

In [5]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x and y

In [6]:
np.where?

In [7]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [8]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(np.where(x>5, x, 0))

[[0 0 0]
 [0 0 6]
 [7 8 9]]


In [10]:
print(np.array([1,2,3]))

[1 2 3]


In [11]:
print(type)

<class 'type'>


In [12]:
print(type(x))

<class 'numpy.ndarray'>


In [13]:
A = np.array([[1,2,3], [4,5,6]])

In [14]:
print(A)

[[1 2 3]
 [4 5 6]]


In [15]:
print(type(A))

<class 'numpy.ndarray'>


In [16]:
print(A.shape)

(2, 3)


In [17]:
print(x.shape)

(3, 3)


In [18]:
print(x.shape[0])

3


In [19]:
 print(np.reshape(A, (3,2)))

[[1 2]
 [3 4]
 [5 6]]


## **Reshape a matrix from column to row vector**

In [20]:
print(np.reshape(A,(1, -1)))

[[1 2 3 4 5 6]]


In [21]:
print(np.reshape(A, (-1, 1)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [22]:
 print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Reshape to two-dimenssion

In [24]:
y = np.array([1,2,3])

In [27]:
print(y[ None, :])

[[1 2 3]]


In [28]:
print(y[:, None])

[[1]
 [2]
 [3]]


In [29]:
print(y[:, np.newaxis])

[[1]
 [2]
 [3]]


# Array dimenssion

In [30]:
print(x.ndim)

2


In [31]:
print(y.ndim)

1


# Data type

In [32]:
print(x.dtype)

int64


In [33]:
c= np.array([1,2,3], dtype=np.float32)

In [34]:
print(c)

[1. 2. 3.]
