<a href="https://colab.research.google.com/github/Mahrokh-Eb/Machine-Learning-With-Python/blob/master/1_1_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
!python --version

Python 3.7.12


In [4]:
print(np.__version__)

1.19.5


In [5]:
#dir(np)

In [6]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x and y

In [7]:
np.where?

In [8]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [9]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(np.where(x>5, x, 0))

[[0 0 0]
 [0 0 6]
 [7 8 9]]


In [11]:
print(np.array([1,2,3]))

[1 2 3]


In [12]:
print(type)

<class 'type'>


In [13]:
print(type(x))

<class 'numpy.ndarray'>


In [14]:
A = np.array([[1,2,3], [4,5,6]])

In [15]:
print(A)

[[1 2 3]
 [4 5 6]]


In [16]:
print(type(A))

<class 'numpy.ndarray'>


In [17]:
print(A.shape)

(2, 3)


In [18]:
print(x.shape)

(3, 3)


In [19]:
print(x.shape[0])

3


In [20]:
 print(np.reshape(A, (3,2)))

[[1 2]
 [3 4]
 [5 6]]


## **Reshape a matrix from column to row vector**

In [21]:
print(np.reshape(A,(1, -1)))

[[1 2 3 4 5 6]]


In [22]:
print(np.reshape(A, (-1, 1)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [23]:
 print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
