In [1]:
from sklearn import datasets
from sklearn.datasets import load_wine
wine = load_wine()

In [2]:
print( wine.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [3]:
print(wine.data)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [4]:
print(wine.data.shape)

(178, 13)


In [5]:
print(wine.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [6]:
print(wine.target_names)

['class_0' 'class_1' 'class_2']


In [7]:
print(wine.data.shape)
print(wine.target.shape)

(178, 13)
(178,)


In [9]:
n_fearure, n_sample = wine.data.shape
print('number of samples: %d' % n_fearure)
print('number of features: %d' %n_sample)

number of samples: 178
number of features: 13


In [13]:
print(wine.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [17]:
x , y = wine.data, wine.target
print(x.shape, y.shape)

(178, 13) (178,)


In [10]:
# step 1: import
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier()

In [18]:
#step 2: fit(train)
clf.fit (x, y)

/Users/mahrokh/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [20]:
# step 3: predict (test)
y_pred = clf.predict(x)

In [25]:
# step 4: evaluate the accuracy
import numpy as np
accuracy = np.mean(y_pred == y)
print(accuracy)

0.9606741573033708
